// Minimal showcase sample data for events and tickets
// Dates are ISO strings; ensure some are upcoming relative to now

const now = new Date();
const dayMs = 24 * 60 * 60 * 1000;

const sampleEvents = [
  {
    id: "evt-1",
    _id: "evt-1",
    slug: "bitcoin-conference-2026",
    eventName: "Bitcoin Conference 2026",
    description: "A multi-day event exploring the future of Bitcoin and decentralized finance.",
    image: "/assets/images/eventImage.png",
    location: "Miami, FL",
    network: "Polygon",
    royaltyFee: 2.5,
    transactionFee: 1.5,
    startDate: new Date(now.getTime() + 7 * dayMs).toISOString(),
    endDate: new Date(now.getTime() + 9 * dayMs).toISOString(),
    aboutExperience: "Join thousands of builders, investors, and creators for keynotes, workshops, and networking.",
    needToKnow: "Bring a valid ID, your wallet app, and comfortable shoes. Doors open at 9 AM.",
    faq: [
      { question: "Is there on-site parking?", answer: "Yes, paid parking is available nearby." },
      { question: "Can I transfer my ticket?", answer: "Yes, transfers are supported up to 24 hours before the event." }
    ],
    totalTickets: 5000,
    soldTickets: 1875,
    tickets: [
      {
        id: "tkt-1a",
        slug: "bitcoin-conference-2026-general-admission",
        image: "/assets/images/eventProduction1.png",
        ticketType: { key: "insiderIO", ticketType: "InsiderIO" },
        ticketTitle: "General Admission",
        totalTickets: 3000,
        validFor: [new Date(now.getTime() + 7 * dayMs).toISOString()],
        sellType: "fixedPrice",
        fixPrice: 120,
        stripeAmount: 120,
        benefits: "Access to all main stage talks and expo floor.",
      },
      {
        id: "tkt-1b",
        slug: "bitcoin-conference-2026-vip",
        image: "/assets/images/eventProduction2.png",
        ticketType: { key: "insiderIO", ticketType: "InsiderIO" },
        ticketTitle: "VIP Pass",
        totalTickets: 500,
        validFor: [new Date(now.getTime() + 7 * dayMs).toISOString(), new Date(now.getTime() + 8 * dayMs).toISOString()],
        sellType: "fixedPrice",
        fixPrice: 350,
        stripeAmount: 350,
        benefits: "VIP lounge, front-row seating, and speaker mixer access.",
      },
    ],
  },
  {
    id: "evt-2",
    _id: "evt-2",
    slug: "defi-summit-2026",
    eventName: "DeFi Summit 2026",
    description: "Dive deep into protocols, security, and real-world adoption of DeFi.",
    image: "/assets/images/eventProduction3.png",
    location: "San Francisco, CA",
    network: "Polygon",
    royaltyFee: 2,
    transactionFee: 1,
    startDate: new Date(now.getTime() + 30 * dayMs).toISOString(),
    endDate: new Date(now.getTime() + 31 * dayMs).toISOString(),
    aboutExperience: "Hands-on workshops with leading protocol teams.",
    needToKnow: "Workshop seating is limited; arrive early.",
    faq: [
      { question: "Are meals included?", answer: "Lunch and coffee are provided both days." },
    ],
    totalTickets: 2000,
    soldTickets: 450,
    tickets: [
      {
        id: "tkt-2a",
        slug: "defi-summit-2026-standard",
        image: "/assets/images/rewardTicketSection.svg",
        ticketType: { key: "insiderIO", ticketType: "InsiderIO" },
        ticketTitle: "Standard",
        totalTickets: 1500,
        validFor: [new Date(now.getTime() + 30 * dayMs).toISOString()],
        sellType: "fixedPrice",
        fixPrice: 99,
        stripeAmount: 99,
        benefits: "Main track access and expo.",
      },
      {
        id: "tkt-2b",
        slug: "defi-summit-2026-premium",
        image: "/assets/images/eventProduction3.png",
        ticketType: { key: "insiderIO", ticketType: "InsiderIO" },
        ticketTitle: "Premium",
        totalTickets: 300,
        validFor: [new Date(now.getTime() + 30 * dayMs).toISOString()],
        sellType: "fixedPrice",
        fixPrice: 199,
        stripeAmount: 199,
        benefits: "Workshop track access + priority seating.",
      },
    ],
  },
  {
    id: "evt-3",
    _id: "evt-3",
    slug: "nft-art-weekend",
    eventName: "NFT Art Weekend",
    description: "Art, music, and experiences at the intersection of culture and NFTs.",
    image: "/assets/images/ticketsApprove.png",
    location: "New York, NY",
    network: "Polygon",
    royaltyFee: 1.5,
    transactionFee: 0.75,
    startDate: new Date(now.getTime() - 2 * dayMs).toISOString(),
    endDate: new Date(now.getTime() + 1 * dayMs).toISOString(),
    aboutExperience: "Immersive installations and live performances by top NFT artists.",
    needToKnow: "Evening sessions may have strobe lights and loud music.",
    faq: [
      { question: "Is there an age restriction?", answer: "All ages welcome; under 16 must be accompanied by an adult." }
    ],
    totalTickets: 1500,
    soldTickets: 1200,
    tickets: [
      {
        id: "tkt-3a",
        slug: "nft-art-weekend-day-pass",
        image: "/assets/images/eventProduction1.png",
        ticketType: { key: "insiderIO", ticketType: "InsiderIO" },
        ticketTitle: "Day Pass",
        totalTickets: 800,
        validFor: [new Date(now.getTime()).toISOString()],
        sellType: "fixedPrice",
        fixPrice: 49,
        stripeAmount: 49,
        benefits: "Single-day gallery and music access.",
      },
      {
        id: "tkt-3b",
        slug: "nft-art-weekend-weekend-pass",
        image: "/assets/images/eventProduction3.png",
        ticketType: { key: "insiderIO", ticketType: "InsiderIO" },
        ticketTitle: "Weekend Pass",
        totalTickets: 200,
        validFor: [new Date(now.getTime()).toISOString(), new Date(now.getTime() + 1 * dayMs).toISOString()],
        sellType: "fixedPrice",
        fixPrice: 129,
        stripeAmount: 129,
        benefits: "Full-weekend access and backstage showcase.",
      },
    ],
  },
];

export default sampleEvents;


